### ISSUE TITLE
Error: Cannot find module '@/constants'

### ISSUE THREAD

**Issue by roninaruka** [denbon05/fastify-lcache#50]
not startup application 

```
Error: Cannot find module '@/constants'
Require stack:
- APP_PATH/node_modules/.pnpm/fastify-lcache@2.1.3_fastify@4.15.0/node_modules/fastify-lcache/dist/index.js
- APP_PATH/src/app.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (APP_PATH/node_modules/.pnpm/@cspotcode+source-map-support@0.8.1/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (APP_PATH/node_modules/.pnpm/fastify-lcache@2.1.3_fastify@4.15.0/node_modules/fastify-lcache/dist/index.js:29:32)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at nodeDevHook (APP_PATH/node_modules/.pnpm/node-dev@7.4.3/node_modules/node-dev/lib/hook.js:54:7)
    at require.extensions.<computed> (APP_PATH/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.9.2_typescript@5.2.2/node_modules/ts-node/src/index.ts:1608:43)
[ERROR] 00:55:44 Error: Cannot find module '@/constants'
Require stack:
- APP_PATH/node_modules/.pnpm/fastify-lcache@2.1.3_fastify@4.15.0/node_modules/fastify-lcache/dist/index.js
- APP_PATH/src/app.ts
```

**Comment by denbon05** [comment]
@roninaruka thanks for pointing this out :)
[fixed in patch v2.1.5](https://github.com/denbon05/fastify-lcache/pull/53)
